### ISSUE TITLE
Resizing some gif frames causes a panic

### ISSUE THREAD

**Issue by jessicamaybe** [jay3332/ril#38]
When trying to resize certain gifs I'll get a panic. Some gifs work, some gifs don't work. Not sure what the pattern is

```
thread 'main' panicked at /home/jessica/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ril-0.10.2/src/resize.rs:103:77:
called `Result::unwrap()` on an `Err` value: InvalidBufferSize
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::result::unwrap_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1679:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/result.rs:1102:23
   4: ril::resize::FilterType::resize
             at /home/jessica/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ril-0.10.2/src/resize.rs:103:19
   5: ril::resize::resize
             at /home/jessica/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ril-0.10.2/src/resize.rs:146:14
   6: ril::image::Image<P>::resize
             at /home/jessica/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ril-0.10.2/src/image.rs:1056:21
   7: gifbugtest::main
             at ./src/main.rs:11:9
   8: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5

```

Sample code:
```
use ril::prelude::*;


fn main() -> ril::Result<()> {
    let mut output = ImageSequence::<Rgba>::new();

    for frame in ImageSequence::<Rgba>::open("little-caesars-pretzel-crust-pizza2.gif")? {

        let mut frame = frame?;

        frame.resize(500, 500, ResizeAlgorithm::Nearest);

        output.push_frame(frame);
    }

    output.save_inferred("resized.gif")?;
    Ok(())

}
```

Sample gif (yeah i know lol):
![little-caesars-pretzel-crust-pizza2](https://github.com/user-attachments/assets/19c71dc4-64da-4514-8c74-f25945c77917)

**Comment by jay3332** [comment]
This seemed to be a bug in GIF encoding entirely. Should be fixed in https://github.com/jay3332/ril/commit/3f9e3e28d3ff49b54e82fc828c62575d465acd97
